name: Build macOS .app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if test -f requirements.txt; then pip install -r requirements.txt; fi

    - name: Build app with PyInstaller
      run: |
        pyinstaller --onefile --windowed cool_script.py

    - name: Upload built app
      uses: actions/upload-artifact@v3
      with:
        name: cool_script_app
        path: dist/cool_script
